FROM public.ecr.aws/docker/library/python:3.9-slim

WORKDIR /app

COPY docker/requirements-api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY Src/api.py .

ENV PYTHONUNBUFFERED=TRUE

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
